version: '3'

vars:
  PYTHON: "venv/bin/python"
  PIP: "venv/bin/pip"

tasks:
  # Install development dependencies
  install:
    desc: "Install development dependencies"
    cmds:
      - "{{.PIP}} install black isort flake8 mypy"

  # Format Python code
  format:
    desc: "Format Python code with Black and isort"
    cmds:
      - "{{.PYTHON}} -m black src/"
      - "{{.PYTHON}} -m isort src/"

  # Check formatting
  check:
    desc: "Check Python code formatting"
    cmds:
      - "{{.PYTHON}} -m black --check src/"
      - "{{.PYTHON}} -m isort --check-only src/"

  # Lint code
  lint:
    desc: "Lint Python code"
    cmds:
      - "{{.PYTHON}} -m flake8 src/"

  # Type check
  type-check:
    desc: "Type check Python code"
    cmds:
      - "{{.PYTHON}} -m mypy src/"

  # Build package for PyPI
  build:
    desc: "Build package for PyPI"
    cmds:
      - "{{.PIP}} install build twine"
      - "{{.PYTHON}} -m build"
      - "echo 'Package built in dist/ directory'"

  # Clean build artifacts
  clean:
    desc: "Clean build artifacts"
    cmds:
      - "rm -rf build/"
      - "rm -rf dist/"
      - "rm -rf *.egg-info/"
      - "find . -type d -name __pycache__ -exec rm -rf {} +"
      - "find . -type f -name '*.pyc' -delete"

  # Documentation tasks
  docs-install:
    desc: "Install documentation dependencies"
    cmds:
      - "{{.PIP}} install -r docs/requirements.txt"

  docs-build:
    desc: "Build documentation"
    cmds:
      - "cd docs && make html"
      - "echo 'Documentation built in docs/_build/html/'"

  docs-serve:
    desc: "Serve documentation locally"
    cmds:
      - "cd docs && make serve"
      - "echo 'Documentation available at http://localhost:8000'"

  docs-clean:
    desc: "Clean documentation build artifacts"
    cmds:
      - "cd docs && make clean"
      - "rm -rf docs/_build/"

  # docs-deploy removed - using Read the Docs for deployment

  # Combined documentation workflow
  docs:
    desc: "Full documentation workflow (install, build, serve)"
    cmds:
      - task: docs-install
      - task: docs-build
      - task: docs-serve

  # Development workflow
  dev:
    desc: "Full development workflow (format, lint, type-check, build)"
    cmds:
      - task: format
      - task: check
      - task: lint
      - task: type-check
      - task: build

  # Complete workflow
  all:
    desc: "Complete workflow (format, lint, type-check, build, docs)"
    cmds:
      - task: format
      - task: check
      - task: lint
      - task: type-check
      - task: build
      - task: docs-build
